require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/medical_records", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # MedicalRecord. As you add validations to MedicalRecord, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      MedicalRecord.create! valid_attributes
      get medical_records_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      medical_record = MedicalRecord.create! valid_attributes
      get medical_record_url(medical_record)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_medical_record_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      medical_record = MedicalRecord.create! valid_attributes
      get edit_medical_record_url(medical_record)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new MedicalRecord" do
        expect {
          post medical_records_url, params: { medical_record: valid_attributes }
        }.to change(MedicalRecord, :count).by(1)
      end

      it "redirects to the created medical_record" do
        post medical_records_url, params: { medical_record: valid_attributes }
        expect(response).to redirect_to(medical_record_url(MedicalRecord.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new MedicalRecord" do
        expect {
          post medical_records_url, params: { medical_record: invalid_attributes }
        }.to change(MedicalRecord, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post medical_records_url, params: { medical_record: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested medical_record" do
        medical_record = MedicalRecord.create! valid_attributes
        patch medical_record_url(medical_record), params: { medical_record: new_attributes }
        medical_record.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the medical_record" do
        medical_record = MedicalRecord.create! valid_attributes
        patch medical_record_url(medical_record), params: { medical_record: new_attributes }
        medical_record.reload
        expect(response).to redirect_to(medical_record_url(medical_record))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        medical_record = MedicalRecord.create! valid_attributes
        patch medical_record_url(medical_record), params: { medical_record: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested medical_record" do
      medical_record = MedicalRecord.create! valid_attributes
      expect {
        delete medical_record_url(medical_record)
      }.to change(MedicalRecord, :count).by(-1)
    end

    it "redirects to the medical_records list" do
      medical_record = MedicalRecord.create! valid_attributes
      delete medical_record_url(medical_record)
      expect(response).to redirect_to(medical_records_url)
    end
  end
end
